"use client"
import { useMemo, useState } from "react"
import Link from "next/link"
import { ArrowRight, FileSearch, FileText, Search, ShieldCheck, Users } from "lucide-react"
import { AppShell } from "@/components/shell/app-shell"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { MOCK_ANALYSES } from "@/mock/analyses"

const results = [{ title: "Política PR-04 · Contratações de tecnologia", type: "Política", context: "Governança · atualizada há 2 dias", href: "/policies", icon: ShieldCheck }, { title: "Marina Costa", type: "Pessoa", context: "Jurídico e Risco · ativo", href: "/profile", icon: Users }, { title: "Edital Alpha 014/2026", type: "Documento", context: "Concorrência 014/2026 · 42 páginas", href: "/analyses/an_demo", icon: FileText }, ...MOCK_ANALYSES.map((item) => ({ title: item.title, type: "Análise", context: `${item.orgao} · análise rastreável`, href: `/analyses/${item.id}`, icon: FileSearch }))]
export function SearchPage() { const [query, setQuery] = useState(""); const filtered = useMemo(() => results.filter((item) => `${item.title} ${item.type} ${item.context}`.toLowerCase().includes(query.toLowerCase())), [query]); return <AppShell title="Busca global" description="Análises, documentos, pessoas, times, políticas e relatórios"><div className="mx-auto flex max-w-4xl flex-col gap-6"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-primary">Descoberta · ⌘K</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">Encontre qualquer decisão</h2><p className="mt-2 text-sm text-muted-foreground">A busca consulta o contexto do tenant e agrupa os resultados por tipo.</p></div><Card><CardContent className="p-4"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar análises, políticas e pessoas" className="pl-9" /></div></CardContent></Card><div className="flex flex-col gap-2"><p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{query ? `${filtered.length} resultados` : "Resultados recentes"}</p>{filtered.map((item) => { const Icon = item.icon; return <Link key={`${item.type}-${item.title}`} href={item.href}><Card className="transition-colors hover:border-primary/40"><CardContent className="flex items-center gap-4 p-4"><div className="flex size-9 items-center justify-center rounded-md bg-primary/10 text-primary"><Icon className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.title}</p><p className="mt-1 truncate text-xs text-muted-foreground">{item.context}</p></div><Badge variant="outline">{item.type}</Badge><ArrowRight className="size-4 text-muted-foreground" /></CardContent></Card></Link> })}</div></div></AppShell> }
