"use client"
import { useState } from "react"
import { Bell, Building2, Check, LockKeyhole, Moon, Palette, ShieldCheck, Sun, Users } from "lucide-react"
import { AppShell } from "@/components/shell/app-shell"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useTheme } from "next-themes"

const sections = [{ title: "Minha conta", description: "Identidade e informações de acesso.", icon: ShieldCheck }, { title: "Organização", description: "Dados do tenant e contexto operacional.", icon: Building2 }, { title: "Preferências", description: "Aparência, idioma e notificações.", icon: Palette }, { title: "Segurança", description: "Senha, sessões e proteção da conta.", icon: LockKeyhole }, { title: "Equipe", description: "Times, membros e permissões.", icon: Users }]
export function SettingsPage() { const { theme, setTheme } = useTheme(); const [saved, setSaved] = useState(false); return <AppShell title="Configurações" description="Conta, organização, preferências e segurança"><div className="mx-auto flex max-w-5xl flex-col gap-6"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-primary">Sistema · Administração</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">Configurações</h2><p className="mt-2 text-sm text-muted-foreground">Um lugar para administrar o contexto do tenant sem misturar regras de análise.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{sections.map(({ title, description, icon: Icon }) => <Card key={title} className="transition-colors hover:border-primary/40"><CardContent className="flex flex-col gap-3 p-4"><Icon className="size-5 text-primary" /><p className="text-sm font-medium">{title}</p><p className="text-xs leading-5 text-muted-foreground">{description}</p></CardContent></Card>)}</div><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><Card><CardHeader><CardTitle className="text-base">Minha conta</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><div className="flex flex-col gap-2"><Label htmlFor="settings-name">Nome</Label><Input id="settings-name" defaultValue="Marina Costa" /></div><div className="flex flex-col gap-2"><Label htmlFor="settings-email">E-mail</Label><Input id="settings-email" defaultValue="marina.costa@empresa-demo.com" type="email" /></div><div className="flex flex-col gap-2 sm:col-span-2"><Label htmlFor="settings-role">Cargo</Label><Input id="settings-role" defaultValue="Diretora de Jurídico e Risco" /></div></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Aparência</CardTitle></CardHeader><CardContent className="flex flex-col gap-3"><div className="grid grid-cols-3 gap-2">{[{ value: "light", label: "Claro", icon: Sun }, { value: "dark", label: "Escuro", icon: Moon }, { value: "system", label: "Sistema", icon: Palette }].map(({ value, label, icon: Icon }) => <Button key={value} variant={theme === value ? "default" : "outline"} className="flex-col gap-2 py-3" onClick={() => setTheme(value)}><Icon className="size-4" /><span className="text-xs">{label}</span></Button>)}</div><div className="flex items-center justify-between rounded-lg border p-3"><div className="flex items-center gap-3"><Bell className="size-4 text-muted-foreground" /><div><p className="text-sm font-medium">Notificações</p><p className="text-xs text-muted-foreground">Eventos de análise e revisão</p></div></div><Switch defaultChecked /></div><Button onClick={() => setSaved(true)}>{saved ? <><Check data-icon="inline-start" />Alterações salvas</> : "Salvar alterações"}</Button></CardContent></Card></div></div></AppShell> }
