"use client"

import { useEffect, useState } from "react"
import { Bell, Building2, Check, LockKeyhole, Moon, Palette, ShieldCheck, Sun, Users } from "lucide-react"
import { toast } from "sonner"
import { useTheme } from "next-themes"
import { AppShell } from "@/components/shell/app-shell"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

const sections = [{ title: "Minha conta", description: "Identidade e informações de acesso.", icon: ShieldCheck }, { title: "Organização", description: "Dados do tenant e contexto operacional.", icon: Building2 }, { title: "Preferências", description: "Aparência, idioma e notificações.", icon: Palette }, { title: "Segurança", description: "Senha, sessões e proteção da conta.", icon: LockKeyhole }, { title: "Equipe", description: "Times, membros e permissões.", icon: Users }]
export function SettingsPage() {
  const { theme, setTheme } = useTheme(); const [saved, setSaved] = useState(false); const [name, setName] = useState("Marina Costa"); const [email, setEmail] = useState("marina.costa@empresa-demo.com"); const [notifications, setNotifications] = useState(true)
  useEffect(() => { const raw = window.localStorage.getItem("lexguard:settings:v1"); if (raw) { try { const data = JSON.parse(raw); setName(data.name ?? name); setEmail(data.email ?? email); setNotifications(data.notifications ?? true) } catch {} } }, [])
  function save() { if (!name.trim() || !email.includes("@")) { toast.error("Revise os campos", { description: "Informe um nome e um e-mail válido." }); return } window.localStorage.setItem("lexguard:settings:v1", JSON.stringify({ name, email, notifications })); setSaved(true); toast.success("Configurações salvas"); setTimeout(() => setSaved(false), 2200) }
  return <AppShell title="Configurações" description="Conta, organização, preferências e segurança"><div className="mx-auto flex max-w-5xl flex-col gap-6"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-primary">Sistema · Administração</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">Configurações</h2><p className="mt-2 text-sm text-muted-foreground">Um lugar para administrar o contexto do tenant sem misturar regras de análise.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{sections.map(({ title, description, icon: Icon }) => <button key={title} type="button" onClick={() => document.getElementById(title === "Preferências" ? "appearance" : "account")?.scrollIntoView({ behavior: "smooth" })} className="text-left"><Card className="h-full transition-colors hover:border-primary/40"><CardContent className="flex flex-col gap-3 p-4"><Icon className="size-5 text-primary" /><p className="text-sm font-medium">{title}</p><p className="text-xs leading-5 text-muted-foreground">{description}</p></CardContent></Card></button>)}</div><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><Card id="account"><CardHeader><CardTitle className="text-base">Minha conta</CardTitle></CardHeader><CardContent className="grid gap-4"><div className="flex flex-col gap-2"><Label htmlFor="settings-name">Nome</Label><Input id="settings-name" value={name} onChange={(event) => setName(event.target.value)} /></div><div className="flex flex-col gap-2"><Label htmlFor="settings-email">E-mail</Label><Input id="settings-email" value={email} onChange={(event) => setEmail(event.target.value)} type="email" /></div><Button onClick={save}>{saved ? <Check data-icon="inline-start" /> : null}{saved ? "Salvo" : "Salvar alterações"}</Button></CardContent></Card><Card id="appearance"><CardHeader><CardTitle className="text-base">Aparência e notificações</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><div className="grid grid-cols-3 gap-2">{[{ value: "light", label: "Claro", icon: Sun }, { value: "dark", label: "Escuro", icon: Moon }, { value: "system", label: "Sistema", icon: Palette }].map(({ value, label, icon: Icon }) => <Button key={value} type="button" variant={theme === value ? "default" : "outline"} onClick={() => setTheme(value)}><Icon data-icon="inline-start" />{label}</Button>)}</div><div className="flex items-center justify-between rounded-lg border p-3"><div><p className="text-sm font-medium">Notificações da operação</p><p className="text-xs text-muted-foreground">Receber alertas sobre análises e tarefas.</p></div><Switch checked={notifications} onCheckedChange={setNotifications} aria-label="Ativar notificações" /></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><Bell className="size-4 text-primary" />As preferências ficam salvas neste navegador.</div></CardContent></Card></div></div></AppShell>
}
