"use client"

import Link from "next/link"
import { useState } from "react"
import { ArrowRight, Check, FileText, ShieldCheck, UploadCloud } from "lucide-react"
import { AppShell } from "@/components/shell/app-shell"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

const steps = ["Documentos", "Política de risco", "Revisão", "Processamento"]
export function NewAnalysis() { const [step, setStep] = useState(0); const [file, setFile] = useState(false); return <AppShell title="Nova análise" description="Configure o contexto antes de iniciar o processamento"><div className="mx-auto flex max-w-4xl flex-col gap-6"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-primary">Fluxo guiado · {step + 1}/4</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">Prepare uma nova decisão</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Cada análise se torna um chat persistente com documentos, evidências e decisões rastreáveis.</p></div><div className="grid gap-2 md:grid-cols-4">{steps.map((label, index) => <div key={label} className={`flex items-center gap-2 rounded-md border p-3 text-xs ${index === step ? "border-primary bg-primary/5 text-primary" : index < step ? "border-success/40 bg-success-soft text-success-foreground" : "text-muted-foreground"}`}><span className="flex size-6 items-center justify-center rounded-full border font-mono">{index < step ? <Check /> : index + 1}</span>{label}</div>)}</div><Card><CardHeader><CardTitle className="text-base">{steps[step]}</CardTitle><p className="text-sm text-muted-foreground">{step === 0 ? "Carregue o edital e anexos que farão parte do contexto." : step === 1 ? "Selecione as políticas que devem orientar a análise." : step === 2 ? "Confirme os documentos e o escopo antes de iniciar." : "Acompanhe eventos observáveis enquanto o copiloto processa."}</p></CardHeader><CardContent className="flex flex-col gap-5">{step === 0 ? <button type="button" onClick={() => setFile(true)} className="flex min-h-52 flex-col items-center justify-center gap-3 rounded-lg border border-dashed bg-muted/30 text-center transition-colors hover:border-primary hover:bg-primary/5"><div className="flex size-12 items-center justify-center rounded-full bg-primary/10 text-primary"><UploadCloud /></div><span className="text-sm font-medium">{file ? "Edital-014-2026.pdf pronto" : "Selecione ou arraste o edital"}</span><span className="text-xs text-muted-foreground">PDF, DOCX ou TXT · até 50 MB</span></button> : <div className="flex flex-col gap-3">{["Edital principal", "Anexos e termos de referência", "Política padrão de contratação"].map((item) => <div key={item} className="flex items-center gap-3 rounded-md border p-4"><FileText className="size-4 text-primary" /><span className="flex-1 text-sm">{item}</span><Badge variant="secondary"><ShieldCheck data-icon="inline-start" /> Vinculado</Badge></div>)}</div>}<div className="flex items-center justify-between border-t pt-5"><Button variant="ghost" render={<Link href="/analyses" />}>Cancelar</Button><Button onClick={() => setStep((current) => Math.min(3, current + 1))}>{step === 3 ? "Iniciar processamento" : "Continuar"}<ArrowRight data-icon="inline-end" /></Button></div></CardContent></Card></div></AppShell> }
