"use client"
import Link from "next/link"
import { useState } from "react"
import { ArrowRight, ShieldCheck } from "lucide-react"
import { useAuth } from "@/features/auth/auth-provider"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export default function RegisterPage() { const { register } = useAuth(); const [form, setForm] = useState({ name: "", email: "", password: "", organization: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const update = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement>) => setForm((current) => ({ ...current, [key]: event.target.value })); async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); setLoading(true); try { await register({ ...form, role: "admin" }); window.location.href = "/" } catch (exception) { setError(exception instanceof Error ? exception.message : "Não foi possível criar a conta.") } finally { setLoading(false) } } return <main className="flex min-h-screen items-center justify-center bg-background p-4"><Card className="w-full max-w-md"><CardHeader><div className="flex size-10 items-center justify-center rounded-lg bg-primary text-primary-foreground"><ShieldCheck className="size-5" /></div><p className="mt-4 font-mono text-[10px] uppercase tracking-[0.18em] text-primary">LexGuard · Primeiro acesso</p><CardTitle className="text-2xl">Crie sua conta</CardTitle><p className="text-sm text-muted-foreground">Comece com um tenant vazio e pronto para configurar.</p></CardHeader><CardContent><form className="flex flex-col gap-4" onSubmit={submit}>{([['name','Nome'],['email','E-mail'],['organization','Nome da empresa'],['password','Senha']] as const).map(([key,label]) => <div className="flex flex-col gap-2" key={key}><Label htmlFor={key}>{label}</Label><Input id={key} type={key === 'password' ? 'password' : key === 'email' ? 'email' : 'text'} value={form[key]} onChange={update(key)} required minLength={key === 'password' ? 8 : undefined} /></div>)}{error ? <p className="text-sm text-destructive" role="alert">{error}</p> : null}<Button disabled={loading}>{loading ? "Criando conta…" : "Criar conta"}<ArrowRight data-icon="inline-end" /></Button><p className="text-center text-sm text-muted-foreground">Já possui conta? <Link className="text-primary hover:underline" href="/login">Entrar</Link></p></form></CardContent></Card></main> }
