"use client"

import { ExternalLink, ShieldAlert, Users } from "lucide-react"
import { MOCK_POLICIES } from "@/mock/policies"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import type { RuntimeAnalysis } from "@/types/analysis-runtime"

export function DecisionContext({ analysis }: { analysis: RuntimeAnalysis }) {
  const recommendation = analysis.recommendation === "ADVANCE" ? "AVANÇAR" : analysis.recommendation === "NOT_PRIORITY" ? "NÃO PRIORIZAR" : "REVISAR"
  return <div className="flex flex-col gap-4">
    <Card><CardHeader><CardTitle className="text-sm">Decision Context</CardTitle></CardHeader><CardContent className="flex flex-col gap-4">
      <div><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Recomendação</p><Badge className="mt-2 bg-warning-soft text-warning-foreground" variant="secondary">{recommendation}</Badge></div>
      <div className="rounded-xl border bg-muted/20 p-4"><div className="flex items-center justify-between"><div><p className="text-xs text-muted-foreground">Risk Score</p><p className="mt-1 font-mono text-2xl font-semibold">{analysis.riskScore}/100</p></div><div className="flex size-10 items-center justify-center rounded-full bg-primary/10 text-primary"><ShieldAlert className="size-5" /></div></div><div className="mt-3 h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${analysis.riskScore}%` }} /></div></div>
      <div><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Resumo do Gemini</p><p className="mt-2 rounded-lg border bg-muted/20 p-3 text-xs leading-5">{analysis.summary || "O resultado ainda está sendo consolidado."}</p></div>
      <div><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Evidências do Gemini</p><div className="mt-2 space-y-2">{analysis.evidences?.length ? analysis.evidences.map((evidence) => <div key={evidence.id} className="rounded-lg border p-3"><p className="text-xs font-medium">{evidence.label}{evidence.page ? ` · p. ${evidence.page}` : ""}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{evidence.excerpt}</p></div>) : <p className="rounded-lg border p-3 text-xs text-muted-foreground">Nenhuma evidência foi retornada.</p>}</div></div>
      <div><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Validação em fontes públicas</p><div className="mt-2 space-y-2">{analysis.validationChecks?.length ? analysis.validationChecks.map((check) => <div key={check.source} className="rounded-lg border p-3"><div className="flex items-center justify-between gap-2"><span className="text-xs font-medium">{check.source}</span><Badge variant="outline" className="text-[10px]">{check.status}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{check.detail}</p><a className="mt-1 inline-flex text-[11px] text-primary hover:underline" href={check.url} target="_blank" rel="noreferrer">Abrir fonte oficial</a></div>) : <p className="rounded-lg border p-3 text-xs text-muted-foreground">A validação pública será executada após o upload real.</p>}</div></div>
      <div><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Principais riscos</p><div className="mt-2 space-y-2">{analysis.conflicts?.length ? analysis.conflicts.map((conflict) => <RiskItem key={conflict.id} text={conflict.title} />) : <p className="rounded-lg border p-3 text-xs text-muted-foreground">Nenhum conflito identificado pelo Gemini.</p>}</div></div>
      <div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Política</p><p className="mt-1 text-sm font-medium">{analysis.policyName}</p></div><Badge variant="outline">3 regras</Badge></div><div className="rounded-lg border bg-primary/5 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Base jurídica pública</p><div className="mt-2 flex flex-col gap-1">{MOCK_POLICIES.find((policy) => policy.name === analysis.policyName)?.sources?.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-xs text-primary hover:underline">{source.label}<ExternalLink className="size-3" /></a>)}</div></div>
      <div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Conflitos</p><p className="mt-1 text-sm font-medium">{analysis.conflictCount}</p></div><div><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Evidências</p><p className="mt-1 text-sm font-medium">{analysis.evidenceCount}</p></div></div>
      <div className="flex items-center gap-2 rounded-lg border p-3"><Users className="size-4 text-muted-foreground" /><div><p className="text-xs text-muted-foreground">Responsável</p><p className="text-sm font-medium">{analysis.responsible}</p></div></div>
    </CardContent></Card>
  </div>
}
function RiskItem({ text }: { text: string }) { return <div className="flex items-center gap-2 rounded-lg border p-2.5"><span className="size-2.5 rounded-full bg-critical" /><span className="text-xs">{text}</span></div> }
